settings:
  dry_run: true
  market_window:
    end: '10:00'
    start: 09:00
slack:
  webhook_url: https://hooks.slack.com/services/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
watchlist:
  RELIANCE:
    atr_threshold: 2.0
    direction: LONG
    rvol_threshold: 1.5
    tag: Energy
    token: 738561
